# Generated by Django 5.2.6 on 2025-09-14 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre/s')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido/s')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Nacimiento')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Fallecimiento')),
                ('biography', models.TextField(blank=True, verbose_name='Biografía')),
                ('semblance', models.TextField(blank=True, verbose_name='Semblanza')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la clasificación')),
            ],
        ),
        migrations.CreateModel(
            name='Drawer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del cajón')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del estante')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del género')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='¿Cuándo inicia?')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='¿Cuándo termina?')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_users.classification', verbose_name='Clasificación')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Subtítulo')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='Volumen')),
                ('editorial', models.CharField(max_length=100, verbose_name='Editorial')),
                ('cover', models.CharField(choices=[('hard', 'Dura'), ('soft', 'Blanda')], default='soft', max_length=10, verbose_name='Tipo de portada')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/pdfs/', verbose_name='Archivo PDF')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_users.author', verbose_name='Autor')),
                ('drawer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_users.drawer', verbose_name='Cajón')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_users.gender', verbose_name='Género')),
            ],
        ),
        migrations.AddField(
            model_name='drawer',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_users.shelf', verbose_name='Estante'),
        ),
    ]
