# Generated by Django 5.2.6 on 2025-09-21 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_drawer_user_alter_shelf_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(blank=True, choices=[('hard', 'Dura'), ('soft', 'Blanda')], default='soft', max_length=10, verbose_name='Tipo de portada'),
        ),
        migrations.AlterField(
            model_name='book',
            name='drawer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.drawer', verbose_name='Cajón'),
        ),
    ]
