# Generated by Django 5.2.6 on 2025-09-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_book_cover_alter_book_drawer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='author',
            name='death_date',
        ),
        migrations.AddField(
            model_name='author',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de nacimiento'),
        ),
        migrations.AddField(
            model_name='author',
            name='death_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de fallecimiento'),
        ),
    ]
