# Generated by Django 5.2.6 on 2025-09-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_author_birth_date_remove_author_death_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='authors_images/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books_images/', verbose_name='Imagen'),
        ),
    ]
