# Generated by Django 5.2.6 on 2025-09-21 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_book_drawer_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='drawer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.drawer', verbose_name='Cajón'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.gender', verbose_name='Género'),
        ),
    ]
