# Generated by Django 5.2.6 on 2025-09-23 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_book_drawer_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.classification', verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.shelf', verbose_name='Estante'),
        ),
    ]
