# Generated by Django 5.2.6 on 2025-09-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_book_classification_book_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='access_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de consulta'),
        ),
        migrations.AddField(
            model_name='book',
            name='doi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DOI'),
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Edición'),
        ),
        migrations.AddField(
            model_name='book',
            name='editor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Editor/Compilador'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='book',
            name='place_of_publication',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar de publicación'),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serie/Colección'),
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Traductor'),
        ),
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(blank=True, choices=[('hard', 'Dura'), ('soft', 'Blanda'), ('virtual', 'Virtual')], default='soft', max_length=10, verbose_name='Tipo de portada'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de páginas'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
