# Generated by Django 5.2.6 on 2025-10-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_book_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Número de páginas'),
        ),
    ]
